### ISSUE TITLE
where to find clinical data for TCGA expression data

### ISSUE THREAD

**Issue by Fanglv1990** [taiwenli/TIMER#1]
Helllo，

The URL for TCGA clinical does not work，where to find the clinical data？

Thanks
Grace

**Comment by taiwenli** [comment]
Hi,

You could download all clinical information of TCGA on http://firebrowse.org/ <http://firebrowse.org/>

Thanks,
Taiwen

**Comment by Fanglv1990** [comment]
Hi,
What I really need is the format of clinical data required by your R script. I download clinical data from GDC(https://portal.gdc.cancer.gov/) and  firebrowse(http://firebrowse.org/), but they are in different format. I'm confused.

Thanks
Grace

**Comment by taiwenli** [comment]
Hi,

If you just want to infer the immune abundance, the clinical information is not required. I noticed that there an instruction for downloading clinical data which was posted by Bo Li (bo.li@utsouthwestern.edu <mailto:bo.li@utsouthwestern.edu>), and you could ask him for the detail information. Sorry for the confusion.

Best,
Taiwen

**Comment by Fanglv1990** [comment]
Thank you. The clinical information is not required.
